require("dotenv").config();
const express = require("express");
const cors = require("cors");
const app = express();
const transactionRoutes = require("./routes/transactionRoutes.js");
const connectDB = require("./config/db.js");
const PORT = process.env.PORT || 6500;
connectDB();
app.use(cors());
app.use(express.json());
app.use("/", transactionRoutes);
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
